//
//  Textos.swift
//  PetsCugara
//
//  Created by Viviane Rodrigues Nogueira on 22/11/22.
//

import SwiftUI
import Foundation

struct Topico {
	
	static var banho = Topico("Banho", ["Tutorial":"1. Separe os materiais necessários. \n2. Proteja os ouvidos do seu pet: É importante que antes de começar o banho você proteja os ouvidos proteja os ouvidos do seu animal com algodão para evitar a entrada de água. \n3. Enxágue os pelos: Molhe o corpo do cachorro e por último molhe a cabeça. Atenção com a temperatura da água, ela deve estar de morna para fria. \n4. Aplique o shampoo: Utilizando um produto especial para cães, mais específico para o tipo de pelo do animal, e massageie o pelo. Em seguida, enxágue bem. \n5. Condicionador: Se o seu pet tiver pelos muitos longos, é importante utilizar um condicionador e desembaraçar o pelo com uma escova própria. \n6. Após o banho, limpe os ouvidos do pet com um algodão molhado com um pouco de água, limpando somente até onde você enxergar. \n7. Secagem: Depois de tirar o excesso de água com uma toalha, utilize um secador em temperatura media- baixa para secar o pelo utilizando uma escova.", "Materiais permitidos":"- Escova de dentes (também é importante dar atenção à higiene bucal do seu pet). \n- Produtos especiais para cachorros (shampoo, condicionador). \n- Cortador de unhas.", "Materiais proibidos":"- Produtos destinados a humanos: O pet pode ter alergia aos componentes químicos nesses produtos, podendo gerar ferimentos e até queimaduras. \n- Produtos de limpeza: Jamais utilizar produtos destinados a limpeza da casa, como sabão em pó, detergente, etc. \n- Produtos desenvolvidos para outros animais."],
							  ["Tutorial":"1. Separe os materiais necessários. \n2. Antes de iniciar o banho, lembre-se de proteger os ouvidos do gato com algodão, evitando a entrada de água. \n2. Enxágue: Molhe os pelos com água morna (gatos tendem a ser mais ariscos com banhos, para diminuir isso o ideal é que a água seja de morna para fria, assim o pet fica mais tranquilo). \n3. Shampoo: Aplique um produto especial para gatos e massageie delicadamente, e caso o gato seja de raça com pelos longos, o ideal é utilizar condicionador. \n4. Secagem: Depois de tirar o excesso de água com uma toalha, seque o pelo com o secador em baixa potência escovando o pelo, desatando os nós.", "Materiais permitidos":"- Escova de dentes (também é importante dar atenção à higiene bucal do seu pet). \n- Produtos especiais para o tipo de pelo (shampoo, condicionador se o pelo for muito longo).", "Materiais proibidos":" - Produtos destinados a humanos: Gatos tem o pelo e a pele extremamente sensíveis, por isso não devem ser utilizados. \n- Produtos de limpeza: Jamais utilizar produtos destinados a limpeza da casa, como sabão em pó, detergente, e semelhantes (principalmente em gatos, pois são sensíveis). \n- Produtos desenvolvidos para outros animais."])
	
	static var alimentação = Topico("Alimentação", ["Alimentos permitidos":"Os alimentos abaixo são permitidos dar para seu cachorro, em caso de dúvidas consulte um veterinário. \n\nProteínas: Carne bovina, suína, frango, ovos, peixes, peru e cordeiro. \nCarboidratos: Beterraba, repolho, cenoura, berinjela, chuchu, abóbora, abobrinha, jiló e quiabo. \nVegetais: Batata inglesa, batata doce, mandioca e mandioquinha. \nFrutas: Banana, maçã, pera, kiwi, morango, caju, manga, goiaba e caqui.", "Alimentos proibidos":"A ingestão dos seguintes alimentos pode ser fatal: \n\nLeite de vaca (e seus derivados), cebola, alho, cogumelos, uva, uvas passas, tomate, café, abacate, frutas cítricas, amêndoas, nozes, banana, carambola, sal, vinagre, ovo cru, açúcar, damasco, sementes de frutas e massas fermentadas", "Rotina necessária":"Filhotes de 2 a 4 meses: De 4 a 6 vezes por dia. \nFilhotes de 4 a 8 meses: De 2 a 3 vezes por dia. \nFilhotes acima de 8 meses: Pelo menos 2 vezes por dia. \nAdultos e Seniors: Pelo menos 2 vezes por dia", "Quantidade recomendada":"A quantidade depende da energia e atividade física do cachorro. \n\nDe 3,5 a 7 kg: 63 - 107g. \nDe 7 a 13,5 kg: 107 - 170g. \nDe 13,5 a 22 kg: 170 - 252g. \nDe 22 a 38 kg: 252 - 380g. \nDe 38 a 38,5; 380 - 455g"],
									["Alimentos permitidos":"Os alimentos abaixo são permitidos dar para seu gato, em caso de dúvidas consulte um veterinário. \n\nProteínas: Carne bovina, suína, frango, peru, peixes (não pode ser cru), rã, cordeiro, ovos, coelho e vísceras. \nCarboidratos: Batata doce, ervilhas, arroz, mandioca, inhame, arroz integral e lentilha (carboidratos devem ser oferecidos em poucas quantidades). \nVegetais: Brócolis, abóbora, cenoura, vagem, chuchu, beterraba, alface e abobrinha. \nFrutas: Maçã, melancia, melão, morango, pera e pêssego.", "Alimentos proibidos":"A ingestão dos seguintes alimentos pode ser fatal: \n\nLeite de vaca (e seus derivados), cebola, alho, cogumelos, uva, uvas passas, tomate, café, abacate, frutas cítricas, amêndoas, nozes, banana, carambola, sal, vinagre, ovo cru, sementes de frutas e massas fermentadas", "Rotina necessária":"Filhotes até 12 meses de idade: Visto que os gatos tem muita energia, o gato filhote não precisa de muita comida, e sim várias refeições ao longo do dia. O recomendado é de 3 a 5 vezes por dia. \nAdultos: De 2 a 4 vezes por dia. \nIdosos (a partir de 7 anos): Pelos menos 2 vezes por dia", "Quantidade":"A quantidade depende da energia e atividade física do gato. \n\nDe 1,4 a 2,4 kg: 33 - 47g. \nDe 2,4 a 3,6 kg: 47 - 60g. \nDe 3,6 a 4,7 kg: 60 - 73g. \nDe 4,7 a 7 kg: 73 - 96g"])
	
	static var vacinação = Topico("Vacinação", ["Importância":"As vacinas, assim como nos humanos, desempenham papel importantíssimo na vida dos pets, garantindo saúde e bem estar. Dadas no período correto, as vacinas ajudam a proteger os pets de doenças infecciosas e que são transmissíveis aos seres humanos, como por exemplo, a Raiva e a Leishmaniose (infecção causada por um parasita). Além da importância na saúde do pet, existe também o gasto financeiro, que pode ser evitado com a vacina.", "Vacinas essenciais":"As vacinas não são, assim como muitos acreditam, apenas para a imunização de filhotes, elas devem fazer parte da vida do animal. As vacinas devem ser aplicadas entre as seis e oito semanas de vida, recebendo reforços anuais, para que elas continuem protegendo o animal. \n\nDentre as vacinas que um cachorro deve receber, as seguintes são classificadas como essenciais: Cinomose, Parvovirose, hepatite infecciosa, leptospirose e raiva."],
								  ["Importância":"A imunização periódica do seu bichano é importante, visto que assegura saúde do mesmo e das pessoas ao seu redor, portanto é necessário manter o cartão de vacina em dia. Para ser vacinado, o animal precisa estar saudável, não pode apresentar febre ou outro sintoma.", "Vacinas essenciais":"As vacinas devem começar a serem aplicadas por volta da da oitava semana de vida do gato. É importante ressaltar que as vacinas devem ser aplicadas nos gatos até o final da visa, recebendo doses anuais, de acordo com as recomendações do médico veterinário. \n\nDentre as vacinas classificadas como obrigatórias para os gatos, estão elas: Panleucopenia, raiva, leucemia e rinotraqueíte / calicivirose."])

	static var passeio = Topico("Passeio", ["Acessibilidade":"Saiba em quais locais seu pet pode entrar. Lembrando que não são todos os estabelecimentos que permitem, mas o número de locais tem aumentado a cada dia, então é necessário verificar se o local permite a entrada de animais.\n\n- Lojas de roupas (e móveis), transporte público, museus, praias, praças, shoppings e cinemas.", "Dicas":"Pets no geral necessitam de exercício físico, é importante para a qualidade de vida deles. Passear com o cachorro traz inúmeros benefícios, como a diminuição de problemas de comportamento, como ansiedade e agressividade, melhora da saúde física, obesidade, doenças cardiovasculares, melhora do sono, entre outros. \n\nAlgumas dicas podem otimizar o passeio, entre elas estão: Acostume-o com a coleira sem sair para passear, assim ele entende que a coleira não é uma ameaça. Outra dica que pode ajudar é durante o passeio, caso seu pet encontre com outros animais (por exemplo, se encontrar um cão), pergunte ao tutor se o mesmo gosta de interagir (e se ele permite essa aproximação dos cães) e então relaxe a guia."],
								["Acessibilidade":"Saiba em quais locais seu pet pode entrar. Lembrando que não são todos os estabelecimentos que permitem, mas o número de locais tem aumentado a cada dia, então é necessário verificar se o local permite a entrada de animais.\n\n- Lojas de roupas (e móveis), transporte público, museus, praias, praças, shoppings e cinemas.", "Dicas":"Apesar de gatos serem um pouco arredios quando assunto é passeio, e parte disso se dá pelo fato da coleira, pois gatos tem o toque muito sensível, fazendo com que qualquer coisa que limite seu movimento o incomoda. Mas isso não quer dizer que seu gatinho não possa se exercitar. \n\nOutras formas de fazer seu gato se exercitar além de levá-lo para passear são brinquedos ou acessórios simples, essas são ótimas maneiras de estimular os bichos a se exercitarem, se divertirem e ainda desestressar eles. \nMas se optar pelo passeio, existem maneiras de tornar esse momento o menos estressante possível para seu gato: Uma coleira adequada visto que são sensíveis ao toque, se precisar segurá-lo não o incomodará tanto, sendo as coleiras mais recomendadas as que cobrem o peito do animal. \nOutra dica é ir acostumando o bichano com a coleira, então primeiramente, acostume ele a usar o acessório dentro de casa, dando um passeio pelos cômodos da casa, isso ajuda para que quando ele saia para passear, não se sinta tão incomodado.\nE se mesmo depois disso, seu gato não aceitar a coleira, ou o ambiente, não se preocupe! Nem todo gato é fã de passeios, mas não insista! Insistir com os passeios pode causar traumas para o gato, e isso pode estressá-lo."])
	
	static var primeirosSocorros = Topico("S.O.S", ["Engasgo":"Se possível, abra a boca do animal e tente retirar manualmente o objeto, se o animal se mostrar agressivo, deite-o e dê tapinha nas costas, na altura das patas da frente.", "Envenenamento":"É importante antes de qualquer coisa tentar identificar a causa, isso pode ajudar o veterinário durante o protocolo de atendimento. É indicado se você tiver carvão ativado em casa, oferecer ao animal diluído com uma seringa sem agulha. O carvão ajuda a reduzir a absorção do agente tóxico no organismo do animal.", "Queimaduras e ferimentos":"Em caso de queimaduras, é recomendado lavar a região com água durante pelo menos 10 minutos. Depois, cubra a queimadura com um pano limpo e procure atendimento veterinário, evitando qualquer pomada ou receitas caseiras. \nEm caso de ferimentos como cortes, lave a região com água para evitar infecções, e depois, com um pano limpo, pressione o local para estancar o sangramento até chegar ao veterinário. \nSe o animal sofrer uma fratura, não tente colocar o osso de volta no lugar, o melhor é imobilizar e procurar atendimento o mais rápido possível."],
										  ["Engasgo":"Se possível, abra a boca do animal e tente retirar manualmente o objeto, se o animal se mostrar agressivo, deite-o e dê tapinha nas costas, na altura das patas da frente.", "Envenenamento":"É importante antes de qualquer coisa tentar identificar a causa, isso pode ajudar o veterinário durante o protocolo de atendimento. É indicado se você tiver carvão ativado em casa, oferecer ao animal diluído com uma seringa sem agulha. O carvão ajuda a reduzir a absorção do agente tóxico no organismo do animal.", "Queimaduras e ferimentos":"Em caso de queimaduras, é recomendado lavar a região com água durante pelo menos 10 minutos. Depois, cubra a queimadura com um pano limpo e procure atendimento veterinário, evitando qualquer pomada ou receitas caseiras. \nEm caso de ferimentos como cortes, lave a região com água para evitar infecções, e depois, com um pano limpo, pressione o local para estancar o sangramento até chegar ao veterinário. \nSe o animal sofrer uma fratura, não tente colocar o osso de volta no lugar, o melhor é imobilizar e procurar atendimento o mais rápido possível."])
	
	var nome :String
	var subtopicosDog :[String:String]
	var subtopicosCat :[String:String]

	init (_ nome :String, _ subtopicosDog :[String:String], _ subtopicosCat :[String:String]) {
		self.nome = nome
		self.subtopicosDog = subtopicosDog
		self.subtopicosCat = subtopicosCat
	}
}
